# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TabbarViewController' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'CocoaLumberjack'

  # Pods for TabbarViewController

end
